---
spring:
  zipkin:
    baseUrl: ${vcap.services.config.credentials.zipkin}

info:
  description: Training configuration repo

eureka:
  instance:
    securePortEnabled: true
    hostname: ${vcap.application.uris[0]}
    hostport: 80
    nonSecurePort: 80    
    statusPageUrl: https://${vcap.application.uris[0]}/info
    healthCheckUrl: https://${vcap.application.uris[0]}/health
    secureHealthCheckUrl: https://${vcap.application.uris[0]}/health
    homePageUrl: https://${vcap.application.uris[0]}/

  client:
    enabled: true  
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.url}
    healthcheck:
      enabled: true   