---

info:
  description: Training configuration repo

eureka:
  instance:
    securePortEnabled: true
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80    
    statusPageUrl: https://${eureka.hostname}/info
    healthCheckUrl: https://${eureka.hostname}/health
    homePageUrl: https://${eureka.hostname}/

  client:
    enabled: true  
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.url}
    healthcheck:
      enabled: true   